name: Deploy to WordPress.org
on: workflow_dispatch
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Removing sdk headers
        run: sed --in-place '2,9d' extendify-sdk/extendify-sdk.php
      - name: testing
        run: cat extendify-sdk/extendify-sdk.php
